EM.Web/Areas/Admin/Controllers/IPPoolController.cs
using EM.Factory;
using EM.Helpers;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EM.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    public class IPPoolController : Controller
    {
        // GET: Admin/IPPool
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult PoolData()
        {
            return View();
        }

        [HttpPost]
        public ActionResult PoolData(IP_Pool model)
        {
            var UserId = User.Identity.GetUserId();
            model.CreatedBy = UserId;
            model.LastModBy = UserId;
            string APIURL = string.Format("{0}/{1}", Constants.ApiURL, "ManageIPPool");
            var result = (new APICallHelper()).Post(APIURL, JsonConvert.SerializeObject(model)).StatusCode;
            if (result == System.Net.HttpStatusCode.OK)
            {
                return this.Json(new
                {
                    status = Constants.SuccessTitle,
                    msg = model.Id == 0 ? "IP Pool has been successfully created" : "IP Pool has been successfully updated",
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {

                return this.Json(new
                {
                    status = Constants.ErrorTitle,
                    msg = Constants.ErrorMessage
                }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult GetIPPoolList()
        {
            string APIURL = string.Format("{0}/{1}", ConfigurationManager.AppSettings["ApiURL"], "ManageIPPool");
            var result = (new APICallHelper()).Get(APIURL).Content.ReadAsStringAsync().Result;
            if (result != null)
            {
                var response = Json(JsonConvert.DeserializeObject<List<IP_Pool>>(result.ToString()), JsonRequestBehavior.AllowGet);
                return response;
            }
            else
            {
                return this.Json(new
                {
                    status = Constants.ErrorTitle,
                    message = Constants.ErrorMessage
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult EditIPPool(int id)
        {
            IP_Pool model = new IP_Pool();
            String APIURL = String.Format("{0}/{1}?id={2}", ConfigurationManager.AppSettings["ApiURL"], "ManageIPPool", id);
            var result = (new APICallHelper()).Get(APIURL).Content.ReadAsStringAsync().Result;
            if (result != null)
            {
                var response = JsonConvert.DeserializeObject<IP_Pool>(result.ToString());
                model = response;
            }
            return PartialView("EditIPPool", model);
        }

        [HttpPost]
        public ActionResult DeleteIPPool(int id)
        {
            var APIURL = string.Format("{0}/{1}?id={2}", Constants.ApiURL, "ManageIPPool", id);
            var result = (new APICallHelper()).Delete(APIURL).StatusCode;
            if (result == System.Net.HttpStatusCode.OK)
            {
                return this.Json(new
                {
                    status = Constants.SuccessTitle,
                    msg = "IP Pool has been deleted successfully!",
                }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return this.Json(new
                {
                    status = Constants.ErrorTitle,
                    msg = Constants.ErrorMessage
                }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

EM.Web/Areas/Admin/Views/IPPool/EditIPPool.cshtml
@model EM.Factory.IP_Pool

<div class="modal" role="dialog" id="editIPPool">
    <div class="modal-dialog modal-dialog-centered  modal-sm" role="document">
        <div class="modal-content">
            @using (Ajax.BeginForm("PoolData", "IPPool", new { area = "Admin" }, new AjaxOptions() { HttpMethod = "POST", OnBegin = "return onEditIPPool();", OnSuccess = "onEditIP_PoolSuccess", OnFailure = "onAddIP_PoolFailure" }))
            {

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">
                        Edit
                    </h4>
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            @Html.HiddenFor(m => m.Id)

                            <div class="form-row">
                                <label class="control-label">IP Pool Name</label>
                                @Html.TextBoxFor(m => m.Name, new { id = "txtIPPoolName", @class = "form-control", placeholder = "IP Pool Name",length="64" })
                                <span id="IPPoolError" class="RequiredField"></span>
                                &nbsp;
                            </div>
                        </div>
                    </div>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-warning" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn_default">Update</button>
                </div>

            }
        </div>
    </div>
</div>

EM.Web/Areas/Admin/Views/IPPool/PoolData.cshtml
@model EM.Factory.IP_Pool
@{
    ViewBag.Title = "PoolData";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<ol class="breadcrumb">
    <li><a href="/Admin/Data">Dashboard</a></li>
    <li class="active">Add IP Pool</li>
</ol>

<div class="container-fluid">
    <div class="white-bg-cont">
        <div class="row">
            <div class="col-sm-12">
                <ul class="Master-ctrl-tab">
                    <li><span class="tablinks active">Add IP Pool</span></li>
                </ul>
            </div>
        </div>

        <div class="row">
            <div class="col-sm-5 col-sm-offset-1">
                <div class="row">
                    @using (Ajax.BeginForm("PoolData", "IPPool", new { area = "Admin" }, new AjaxOptions() { HttpMethod = "POST", OnBegin = "return onAddIP_Pool();", OnSuccess = "onAddIP_PoolSuccess", OnFailure = "onAddIP_PoolFailure" }))
                    {
                        <div class="col-lg-12 col-md-12 no-mrg-xs">
                            <div class="white-bg-cont modal-pad-top">

                                <form class="form-horizontal">
                                    <div class="form-group">
                                        <label class="control-label">IP POOL Name</label>
                                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control", @placeholder = "IP POOL Name" })
                                        <span id="lblName" class="RequiredField"></span>

                                    </div>
                                    <div class="form-group">
                                        <div class="col-sm-6" style="margin-right:10px;margin-top:10px;">
                                            <button type="submit" class="btn btn_default">Add</button>
                                            <button type="button" class="btn btn-warning" onclick="Clearcontrol();">Reset</button>

                                        </div>
                                    </div>

                                </form>
                            </div>

                        </div>
                    }
                </div>
            </div>
            <div class="col-sm-4">
                <div class="row">
                    <div class="col-sm-12 col-md-12">
                        <div class="container-fluid margin-top-10 over-x-hidden new_grid-wrap">
                            <table id="pooldataTable" class="display new_grid" style="width:100%"></table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!--Edit IP_POOL Modal-->
<div id="editContainer"></div>

@section PageScript{
    <script src="~/Content/CustomJs/IP_POOL.js?v=05272019"></script>
    <script type="text/javascript">
        $(document).ready(function () {

            preventEnterForSubmittingForm();
        });
    </script>
}