EM.Web/Areas/Admin/Controllers/ManageUserController.cs
using EM.Factory.ViewModels;
using EM.Helpers;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using EM.Factory;
using System.Text;
using System.Text.RegularExpressions;
using System.IO;
using iTextSharp.text;
using iTextSharp.text.pdf;
using iTextSharp.tool.xml;
using EM.Web.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.Owin.Security.DataProtection;
using Microsoft.AspNet.Identity.Owin;
using System.Linq;
using EM.Web.Areas.Admin.Models;
using System.Configuration;
using EM.Web.Utilities;
using EM.Web.Extentions;
using System.Data.SqlClient;
using NMIPayment;
using System.Threading.Tasks;

namespace EM.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ManageUserController : Controller
    {
        MailgunHelper _mailGun = new MailgunHelper();
        Mail oMail = new Mail();
        EmailMarketingDbEntities db = new EmailMarketingDbEntities();

        // GET: Admin/ManageUser
        public ActionResult Index(string id)
        {
            TempData["Id"] = id;
            TempData.Keep("Id");
            return View();
        }

        public ActionResult CreateInvoice(string id)
        {
            InvoiceViewModel model = null;
            string APIURL = string.Format("{0}/{1}?id={2}", Constants.ApiURL, "Invoice/GetNewInvoice", id);
            var apiResult = (new APICallHelper()).Get(APIURL).Content.ReadAsStringAsync().Result;
            if (apiResult != null)
            {
                model = JsonConvert.DeserializeObject<InvoiceViewModel>(apiResult.ToString());
                model.UserId = id;
            }
            model.YearList = DataHelper.GetCreditCardYear(Convert.ToInt32(model.ExpiresYear));
            model.MonthList = DataHelper.GetMonths(Convert.ToInt32(model.ExpiresMonth));
            model.PaymnetTypeList = DataHelper.GetPaymentTypeList(model.PaymentTypeId.ToString());
            return PartialView("CreateInvoice", model);

        }

        [HttpPost]
        public JsonResult CreateInvoice(InvoiceViewModel model)
        {
            if (ModelState.IsValid)
            {
                //string transCode = EM.Helpers.Utilities.GetRandomNumber().ToString();
                string token = null;
                if (model.CardType == null)
                {
                    model.CardType = EM.Helpers.Utilities.getCardType(model.CardNumber);
                }
                using (Payment pp = new Payment())
                {
                    decimal amount = model.AmountCharged != null ? Convert.ToDecimal(model.AmountCharged) : 0;
                    PaymentInfo profile = new PaymentInfo();
                    profile.NavigateUrl = DataHelper.ApplicationUrl() + "/Admin/ManageUser/AdminConfirmPayment";
                    profile.CCNumber = model.CardNumber;
                    var ExpYear = model.ExpiresYear.ToString().Length == 2 ? model.ExpiresYear.ToString() : model.ExpiresYear.ToString().Substring(2, 2);
                    profile.CCEXp = Convert.ToString(model.ExpiresMonth + ExpYear);
                    if (profile.CCEXp.Length == 3)
                    {
                        profile.CCEXp = "0" + profile.CCEXp;
                    }
                    profile.CCV = model.VerificationNo;
                    profile.amount = amount.ToString();
                    profile.billingInfo = new BillingInfo();
                    profile.billingInfo.FirstName = model.NameOnCard.Split(' ')[0];
                    profile.billingInfo.LastName = model.NameOnCard.Split(' ')[1];
                    profile.billingInfo.Address1 = model.Address;
                    profile.billingInfo.City = model.City;
                    profile.billingInfo.State = model.State;
                    profile.billingInfo.Zip = model.Zip;
                    profile.billingInfo.Phone = model.Phone;
                    profile.billingInfo.Fax = model.Phone;
                    profile.billingInfo.Email = model.Email;
                    profile.orderInfo = new OrderInfo();
                    profile.orderInfo.OrderId = model.OrderID;
                    profile.orderInfo.OrderDesc = model.InvoiceType;
                    profile.orderInfo.TaxAmount = 0.00;
                    profile.orderInfo.Amount = Convert.ToDouble(amount);
                    profile.orderInfo.PoNumber = model.UserPaymentProfileId.ToString();
                    profile.orderInfo.CustomField2 = model.CardNumber;
                    profile.orderInfo.CustomField = model.UserId;
                    profile.orderInfo.CustomField3 = model.CardType;

                    //profile.TransCode = transCode;
                    profile.shippingInfo = new ShippingInfo();
                    profile.shippingInfo.FirstName = model.NameOnCard.Split(' ')[0];
                    profile.shippingInfo.LastName = model.NameOnCard.Split(' ')[1];

                    profile.shippingInfo.Address1 = model.Address;
                    profile.shippingInfo.City = model.City;
                    profile.shippingInfo.State = model.State;
                    profile.shippingInfo.Zip = model.Zip;
                    profile.shippingInfo.Phone = model.Phone;
                    profile.shippingInfo.Fax = model.Phone;
                    if (model.AnPaymentProfileId != null)
                    {
                        profile.CustomerVaultId = model.AnPaymentProfileId;
                        token = pp.Transaction(profile, Constants.PaymentProductionMode, false, "Admin Invoice");

                    }
                    else
                    {
                        profile.CustomerVaultId = model.UserId;
                        token = pp.Transaction(profile, Constants.PaymentProductionMode, true, "Admin Invoice");

                    }
                }
                if (token != null && DataHelper.GetTransactionStatus(token) != null && DataHelper.GetTransactionStatus(token) == "100")
                {
                    return this.Json(new
                    {
                        status = Constants.Success,
                        msg = "Invoice has been successfully created",
                    }, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return this.Json(new
                    {
                        status = Constants.Error,
                        msg = "Payment Declined!",
                    }, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return this.Json(new
                {
                    status = Constants.Error,
                    msg = Constants.ErrorMessage,
                }, JsonRequestBehavior.AllowGet);
            }
        }

        [AllowAnonymous]
        public async Task<ActionResult> AdminConfirmPayment()
        {
            ViewBag.TokenId = Request.QueryString["token-id"];
            PaymentStatus paymentStatus = new PaymentStatus();
            InvoiceViewModel model = new InvoiceViewModel();
            paymentStatus = Payment.getPaymentstatus(ViewBag.TokenId, Constants.PaymentProductionMode);
            if (paymentStatus != null)
            {
                paymentStatus.TransCreatedBy = "Admin Invoice";
                DataHelper.updateTransactionDetails(paymentStatus, ViewBag.TokenId);
                if (paymentStatus.result == "1")
                {
                    model.NameOnCard = paymentStatus.FirstName + " " + paymentStatus.LastName;
                    model.City = paymentStatus.City;
                    model.State = paymentStatus.State;
                    model.Zip = paymentStatus.Zip;
                    model.Phone = paymentStatus.Phone;
                    model.CardNumber = paymentStatus.CustomField2;
                    model.ExpiresMonth = Convert.ToInt32(paymentStatus.CCEXp.Substring(0, 2));
                    model.ExpiresYear = Convert.ToInt32(DateTime.Now.Year.ToString().Substring(0, 2) + Convert.ToInt32(paymentStatus.CCEXp.Substring(2, 2))); model.OrderID = paymentStatus.OrderId;
                    model.CreatedById = paymentStatus.CustomField;
                    model.UserId = paymentStatus.CustomField;
                    model.InvoiceType = paymentStatus.OrderDesc;
                    model.UserPaymentProfileId = Convert.ToInt32(paymentStatus.PoNumber);
                    model.AnPaymentProfileId = paymentStatus.customervaultid;
                    model.Email = paymentStatus.Email;
                    model.Address = paymentStatus.Address1;
                    //save user payment profile
                    if (Convert.ToInt32(paymentStatus.PoNumber) == 0)
                    {

                        String URL = string.Format("{0}/{1}", Constants.ApiURL, "Invoice");
                        var response = (new APICallHelper()).Post(URL, JsonConvert.SerializeObject(model)).Content.ReadAsStringAsync().Result;

                    }
                    //save  invoice
                    var invoiceDetails = DataHelper.SaveInvoiceDetails(paymentStatus);
                    //send invoice
                    //SendGridEmails sendGrid = new SendGridEmails();
                    string _creditCardNo = "XXXX-XXXX-XXXX-" + paymentStatus.CCNumber.Substring(paymentStatus.CCNumber.Length - 4);
                    //await _mailGun.sendSingleEmailInvoice(paymentStatus.CustomField,
                    //    paymentStatus.OrderDesc + " Invoice", EmailHtml.getInvoiceSend(paymentStatus.FirstName + " " + paymentStatus.LastName,
                    //    DateTime.Now.ToString("MM/dd/yyyy"), "The following Credit Card has been charged for " + paymentStatus.OrderDesc + " of amount ", paymentStatus.amount, paymentStatus.FirstName + " " + paymentStatus.LastName,

EM.Web/Areas/Admin/Views/ManageUser/AddEditNotes.cshtml
@model EM.Web.Areas.Admin.Models.NoteViewModel

<style type="text/css">
    .preNotePane {
        clear: both;
        padding: 10px 0px;
        border-bottom: 1px solid #ccc;
    }

    .pNdescription {
        clear: both;
        padding: 5px 0 0;
        font-size: 12px;
    }

    .PreNotwrap {
        max-height: 500px;
        overflow-y: auto;
        padding: 15px;
    }
</style>


@using (Ajax.BeginForm("AddNote", "ManageUser", new { area = "Admin" }, new AjaxOptions() { HttpMethod = "POST", OnBegin = "return onAddNote();", OnSuccess = "onAddNoteSucess", OnFailure = "onAddNoteFailure" }))
{
    <div class="app-title">

        <div>
            <span class="text-20">Notes Information</span>
        </div>
    </div>
    <div class="content card">
        <div class="row card-body">


            <div class="col-md-5">
                <div class="row">
                    <p class="mr-l-10"><img src="~/Content/imagesHome/note-ic.png">&nbsp;Add Notes</p>

                    <div class="col-md-12 card account-box even-box-bg-color">
                        @Html.HiddenFor(m => m.newNote.NoteId)
                        @Html.HiddenFor(m => m.newNote.UserId)
                        <div class="form-row">
                            <label class="control-label">Description</label>
                            <a class="creat_new pull-right text-13" href="#!" onclick="Clear();">Clear</a>
                            @Html.TextAreaFor(m => m.newNote.NoteDescription, new { @id = "txtNotes", @class = "form-control", @rows = "5" })
                            @*<textarea type="text" id="" class="form-control" rows="3"></textarea>*@
                            <span id="noteError" class="RequiredField"></span>
                            &nbsp;
                        </div>
                        <div class="form-row">
                            <label class="control-label fa fa-calendar-check-o">Follow Up Date</label>
                            @Html.TextBoxFor(m => m.newNote.FollowUpDate, new { @id = "followDT", @class = "form-control" })
                            @*<input type="text" id="followDT" class="form-control" placeholder="Follow Up" />*@
                            <span id="followError" class="RequiredField"></span>
                            &nbsp;
                        </div>
                        <div class="form-row">
                            <label class="control-label">Follow Up Type</label>
                            @Html.DropDownListFor(x => x.newNote.NoteTypeId, new List<SelectListItem> {
                                                                new SelectListItem { Text = "Call", Value = "1" },
                                                                new SelectListItem { Text = "Text", Value = "2" },
                         new SelectListItem { Text = "Email", Value = "3" },
                         new SelectListItem { Text = "Others", Value = "4" }}, "Select", new { @id = "notetype", @class = "form-control" })

                            <span id="noteTypeError" class="RequiredField"></span>
                            &nbsp;
                        </div>
                        <div class="form-row">
                            <label class="control-label">Time Zone</label>
                            @Html.DropDownListFor(x => x.newNote.TimeZone, Model.TimeZoneList, "--Select--", new { @id="timeZone" ,@class = "form-control" })
                            <span id="timeZoneError" class="RequiredField"></span>
                            &nbsp;
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5" style="margin-left:50px;">
                <div class="row">
                    <p class="mr-l-10"><img src="~/Content/imagesHome/note-ic.png">&nbsp;  Previous Notes:</p>

                    <div class="col-md-12 card account-box odd-box-bg-color">
                        <div class="PreNotwrap text-14">
                            @if (Model.noteList != null && Model.noteList.Count() > 0)
                            {
                                foreach (var item in Model.noteList)
                                {
                                    var data = Newtonsoft.Json.JsonConvert.SerializeObject(item);
                                    var CreatedDate = item.CreatedDate == null ? DateTime.UtcNow : Convert.ToDateTime(item.CreatedDate);
                                    var FormattedDate = string.Format("{0} {1}/{2}/{3}", CreatedDate.Date.ToString("dddd"), CreatedDate.Month, CreatedDate.Day, CreatedDate.Year);
                                    <div class="row preNotePane">
                                        <div class="col-md-12 text-13">
                                            <div class="col-md-8">
                                                <span class="text-bold">
                                                    @FormattedDate by @item.CreatedBy
                                                </span>
                                            </div>
                                            <div class="col-md-3">
                                                <a onclick="editNote(@data)" href="#">Edit</a>
                                                |
                                                <a onclick="deleteNoteConfirmation(@item.NoteId)" href="#">Delete</a>
                                                <br />
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="col-md-10 pNdescription">
                                                <span class="text-13"> @item.NoteDescription</span>

                                            </div>

                                        </div>

                                    </div>
                                }
                            }
                            else
                            {
                                <div class="row">
                                    <div class="col-md-12">
                                        No Record Found
                                    </div>
                                </div>
                            }

                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-5" style="margin-left:550px ; padding:20px!important; ">
                <div class="row">
                    <a type="button" class="btn btn-secondary" href="/Admin/Data"><i class="fa fa-fw fa-lg fa-times-circle"></i>Cancel</a>
                    <button type="submit" class="btn btn-primary"><i class="fa fa-fw fa-lg fa-check-circle" id="btnNoteSubmit"></i><span id="buttonLabel">Add</span></button>
                </div>
            </div>


        </div>
    </div>


}

EM.Web/Areas/Admin/Views/ManageUser/AdminConfirmPayment.cshtml
@{
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

EM.Web/Areas/Admin/Views/ManageUser/BillClient.cshtml
@model EM.Factory.ViewModels.InvoiceViewModel
@{  ViewBag.Title = "Invoice";
    }

@using (Ajax.BeginForm("CreateInvoice", "ManageUser", new { area = "Admin" }, new AjaxOptions() { HttpMethod = "POST", OnBegin = "return onAddBillClientBegin();", OnSuccess = "onAddInvoiceSucess", OnFailure = "onAddInvoiceFailure" }))
{
    <div class="app-title">

        <div>
            <span class="text-20">Bill Client</span>
        </div>
    </div>
    <div class="content card">
        <div class="row card-body">
            <!-- /.col -->
            <div class="col-md-5">
                <div class="row">
                    <p class="mr-l-10"><img src="~/Content/imagesHome/user-icon.png">&nbsp;Invoice Information</p>
                    <div class="col-md-12 card account-box even-box-bg-color">
                        @Html.HiddenFor(x => x.UserId)


                        <div class="row padding-bottom-15 mr-l-r-10">
                            <div class="inner-addon left-addon">
                                <label class="control-label">Amount Charge:</label>
                                @Html.TextBoxFor(x => x.AmountCharged, new { @id = "txtAmount", @class = "form-control", @placeholder = "Amount Charge" })
                                <span class="RequiredField" id="amtError"></span>
                            </div>
                        </div>

                        
                        <div class="row mr-l-r-10 padding-bottom-15">
                            <div class="inner-addon left-addon">
                                <label class="control-label">Charge Type:</label>
                                @Html.DropDownListFor(x => x.PaymentTypeId, Model.PaymnetTypeList, "Charge Type", new { @class = "form-control", @onchange = "$('#InvoiceType').val($('#PaymentTypeId').find('option:selected').text())" })
                                <input type="hidden" name="InvoiceType" id="InvoiceType" />
                                <span class="RequiredField" id="PaymentTypeError"></span>
                            </div>
                        </div>
                        @if (Model.CardNumber == null)
                        {
                            <div class="row mr-l-r-10 padding-bottom-15">
                                <div class="inner-addon left-addon">
                                    <label class="control-label">Card Number:</label>
                                    @Html.TextBoxFor(x => x.CardNumber, new { @class = "form-control", @placeholder = "Card Number" })
                                    <span class="RequiredField" id="CreditError"></span>
                                </div>
                            </div>

                            <div class="row mr-l-r-10 padding-bottom-15">
                                <div class="inner-addon left-addon">
                                    <label class="control-label">Verification Number:</label>
                                    @Html.PasswordFor(x => x.VerificationNo, new { @class = "form-control", @placeholder = "CVV Number", maxlength = "3" })
                                    <span class="RequiredField" id="CreditError"></span>
                                </div>
                            </div>
                            <div class="row mr-l-r-10 padding-bottom-15">
                                <div class="inner-addon left-addon">
                                    <label class="control-label">Expires:</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            @Html.DropDownListFor(x => x.ExpiresMonth, Model.MonthList, "Month", new { @id = "ExpMonth", @class = "form-control" })
                                        </div>

                                        <div class="col-md-6">
                                            @Html.DropDownListFor(x => x.ExpiresYear, Model.YearList, "Year", new { @id = "ExpYear", @class = "form-control" })
                                        </div>
                                    </div>


                                    <span id='ExpMonthError' class='RequiredField'></span>
                                    <span id='ExpYearError' class='RequiredField'></span>

                                </div>
                            </div>
                        }
                        else
                        {
                            <div class="row mr-l-r-10 padding-bottom-15">
                                <div class="inner-addon left-addon">
                                    <label class="control-label">Card Number:</label>
                                    @Html.TextBoxFor(x => x.CardNumber, new { @class = "form-control", @placeholder = "Card Number", @readonly = true })
                                    <span class="RequiredField" id="CreditError"></span>
                                </div>
                            </div>

                            <div class="row mr-l-r-10 padding-bottom-15">
                                <div class="inner-addon left-addon">
                                    <label class="control-label">Verification Number:</label>
                                    @Html.PasswordFor(x => x.VerificationNo, new { @class = "form-control", @placeholder = "CVV Number", maxlength = "3", @readonly = true })
                                    <span class="RequiredField" id="CreditError"></span>
                                </div>
                            </div>
                            <div class="row mr-l-r-10 padding-bottom-15">
                                <div class="inner-addon left-addon">
                                    <label class="control-label">Expires:</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            @Html.TextBoxFor(x => x.ExpiresMonth, new { @id = "ExpMonth", @class = "form-control", @placeholder = "Month", @readonly = true })
                                            @*@Html.DropDownListFor(x => x.ExpiresMonth, Model.MonthList, "Month", new { @id = "ExpMonth", @class = "form-control" })*@
                                        </div>

                                        <div class="col-md-6">
                                            @Html.TextBoxFor(x => x.ExpiresYear, new { @id = "ExpYear", @class = "form-control", @placeholder = "Year", @readonly = true })
                                            @*@Html.DropDownListFor(x => x.ExpiresYear, Model.YearList, "Year", new { @id = "ExpYear", @class = "form-control" })*@
                                        </div>
                                    </div>


                                    <span id='ExpMonthError' class='RequiredField'></span>
                                    <span id='ExpYearError' class='RequiredField'></span>

                                </div>
                            </div>
                        }
                    </div>
                </div>

            </div>
            <!-- /.nav-tabs-custom -->

            <div class="col-md-5" style="margin-left:50px;">
                <div class="row">
                    <p class="mr-l-10"><img src="~/Content/imagesHome/billing-icon.png">&nbsp;Billing Information</p>
                    <div class="col-md-12 card account-box even-box-bg-color">

                        <div class="row padding-bottom-15 mr-l-r-10">
                            <div class="inner-addon left-addon">
                                <label class="control-label">Name On Card:</label>
                                @Html.TextBoxFor(x => x.NameOnCard, new { @id = "txtName", @class = "form-control", @placeholder = "Name On Card" })
                                <span class="RequiredField" id="nameError"></span>
                            </div>
                        </div>
                        <div class="row mr-l-r-10 padding-bottom-15">
                            <div class="inner-addon left-addon">
                                <label class="control-label">Phone:</label>
                                @Html.TextBoxFor(x => x.Phone, new { @id = "txtPhone", @class = "form-control ", @placeholder = "Phone" })
                                <span class="RequiredField" id="PhoneErr"></span>
                            </div>
                        </div>
                        <div class="row mr-l-r-10 padding-bottom-15">
                            <div class="inner-addon left-addon">
                                <label class="control-label">Address:</label>
                                @Html.TextBoxFor(x => x.Address, new { @id = "txtAddress", @class = "form-control", @placeholder = "Address" })
                                <span id="addErr" class="RequiredField"></span>
                            </div>
                        </div>
                        <div class="row mr-l-r-10 padding-bottom-15">
                            <div class="inner-addon left-addon">
                                <label class="control-label">City</label>
                                @Html.TextBoxFor(x => x.City, new { @id = "txtCity", @class = "form-control", @placeholder = "City" })
                                <span id="CityError" class="RequiredField"></span>
                            </div>
                        </div>
                        <div class="row mr-l-r-10 padding-bottom-15">
                            <div class="inner-addon left-addon">
                                <label class="control-label">State</label>
                                @Html.TextBoxFor(x => x.State, new { @id = "txtState", @class = "form-control", @placeholder = "State" })
                                <span id="StateErr" class="RequiredField"></span>
                            </div>
                        </div>
                        <div class="row mr-l-r-10 padding-bottom-15">
                            <div class="inner-addon left-addon">
                                <label class="control-label">Zip</label>
                                @Html.TextBoxFor(x => x.Zip, new { @id = "txtZip", @class = "form-control", @placeholder = "Postal Code" })
                                <span id="zipErr" class="RequiredField"></span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>


            <div class="col-md-5" style="margin-left:550px ; padding:20px!important; ">
                <div class="row">
                    <p class="mr-l-10"></p>
                    <button class="btn btn-primary" type="submit"><i class="fa fa-fw fa-lg fa-check-circle"></i>Create Invoice</button>
                    <a class="btn btn-secondary" href="/Admin/Data"><i class="fa fa-fw fa-lg fa-times-circle"></i>Cancel</a>

                </div>
            </div>
            <div class="col-md-1"></div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>

}

EM.Web/Areas/Admin/Views/ManageUser/CreateList.cshtml
@model EM.Factory.ViewModels.ListViewModel
<div class="modal fade bs-example-modal-sm" id="myModalCreateListPopUp" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Header-->
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick="GetGroup();">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel1">Create a List</h4>
            </div>
            <!--Body-->
            <div class="white-bg-cont">
                <div class="row">
                  <div class="clearfix"></div>
                     <div class="form-group box_group add_file col-lg-12 col-sm-12 col-xs-12 col-ms-12 pad_lr-0">
                         <div class="group1">
                            <div class="col-lg-3 col-sm-3 col-xs-3 col-ms-3">
                                <label>List Name:</label>
                            </div>
                            <div class="col-lg-9 col-sm-9 col-xs-9 col-ms-9 group1">
                            @* @Html.TextBox("txtListName", null, new { @class = "form-control inputtext", @maxlength = "25" })*@

                            @Html.TextBoxFor(m => m.ListName, new { @id = "txtListName", @class = "form-control inputtext", @maxlength = "25" })
                            <span id="lblListName" class="RequiredField"></span>
                            </div>
                         </div>
                         <div class="col-lg-8 col-sm-8 col-xs-8 col-ms-8 col-lg-offset-4 col-sm-offset-4 col-xs-offset-4 col-ms-offset-4 ">
                                <button type="submit" class="waves-effect waves-light btn btn_default" value="Submit" id="btnCreateGroupName" style="margin:3px;" onclick="AddList();"> Add List</button>
                                <button type="submit" class="btn btn-warning waves-effect waves-light" value="Submit" id="btnRestGroup" style="margin:3px;" onclick="ResetList();"> Reset</button>
                         </div>

                          <div class="clearfix"></div>
                      </div>
                        <div>

                        </div>
                        <div class="clearfix"></div>
                </div>
            </div>
            <div class="clearfix"></div>
        </div>
        @*Footer*@

    </div>
    <!--/.Content-->
</div>

@section PageScript{
    <script src="~/Content/CustomJs/ImportContactList.js?v=02042020"></script>
}

EM.Web/Areas/Admin/Views/ManageUser/VerifiedEmailList.cshtml
<ol class="breadcrumb">
    <li><a href="/Admin/Dashboard">Dashboard</a></li>
    <li class="active">Verified Email</li>

</ol>
<div class="white-bg-cont">
    @*Div to bind partial view html*@
    <div class="row">
        <div class="ml-2 col-md-12">
            <div class="ml-2 col-md-12">
                <div id="containerDiv">
                </div>
            </div>

        </div>
    </div>
    </div>