EM.Web/Areas/SalesRep/Models/DashboardViewModel.cs
using EM.Factory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EM.Web.Areas.SalesRep.Models
{
    public class DashboardViewModel
    {
        public usp_getSalesRepTodays_Result todaysData { get; set; }

        public SelectList ClientTypeList { get; set; }

        public SelectList CampaignList { get; set; }

        public SelectList SalesRepList { get; set; }

        public bool canExport { get; set; }

        public bool repActivity { get; set; }
        public SelectList MemberTypeList { get; set; }





    }
}

EM.Web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Configuration;
using System.Web.Mvc;
using EM.Factory;
using EM.Helpers;
using System.Collections.Generic;
using System.Linq;
using EM.Factory.ViewModels;
using EM.Web.Areas.Admin.Models;
using System.Globalization;

namespace EM.Web.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]

    public class DashboardController : Controller
    {
        // GET: Admin/Data
        public ActionResult Index()
        {
            usp_getAdminTodays_Result model = new usp_getAdminTodays_Result();
            AdminTodayViewModel data = new AdminTodayViewModel();
            String APIURL = string.Format("{0}/{1}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard");
            var result = (new APICallHelper()).Get(APIURL).Content.ReadAsStringAsync().Result;
            if (result != null)
            {
                model = JsonConvert.DeserializeObject<usp_getAdminTodays_Result>(result.ToString());
                data.BillDeclined = model.BillDeclined;
                data.ClientBilling = model.ClientBilling;
                data.TotalClient = model.TotalClient;
                data.BillDue = model.BillDue;
                data.PacakagePurchase = model.PacakagePurchase;
                data.PackageDeclined = model.PackageDeclined;
                data.AllClients = model.AllClients;
                data.ClientTypeList = DataHelper.GetClientTypeSelectList(data.ClientType.ToString());
                data.CampaignList = DataHelper.GetCampaignSelectList(data.CampaignType.ToString());
                data.MemberTypeList = DataHelper.GetPlanSelectList(data.MemberType.ToString());

            }
            return View(data);
        }

        [HttpPost]
        public JsonResult getAdminData(string key, string value, string clientType)
        {
            try
            {
                System.Text.StringBuilder APIURL = new System.Text.StringBuilder();
                switch (key)
                {
                    case "Name":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", value, null, null, null, null, null, null, null, null, null, clientType));
                        break;
                    case "Email":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, value, null, null, null, null, null, null, null, null, clientType));
                        break;
                    case "MobileNumber":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, value, null, null, null, null, null, null, null, clientType));
                        break;
                    case "NameOnCard":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, null, value, null, null, null, null, null, null, clientType));
                        break;
                    case "PackageType":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, null, null, value, null, null, null, null, null, clientType));
                        break;
                    case "ReferralCode":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, null, null, null, value, null, null, null, null, clientType));
                        break;
                    case "City":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, null, null, null, null, value, null, null, null, clientType));
                        break;
                    case "State":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, null, null, null, null, null, value, null, null, clientType));
                        break;
                    case "SalesRep":
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, null, null, null, null, null, null, value, null, clientType));
                        break;
                    case "MemberType":
                        value = value == "Select" ? null : value;
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, null, null, null, null, null, null, null, value, clientType));
                        break;
                    default:
                        APIURL.Append(string.Format("{0}/{1}?Name={2}&Email={3}&MobileNumber={4}&NameOnCard={5}&MumberType={6}&ReferralCode={7}&City={8}&State={9}&SalesRep={10}&MemberType={11}&ClientType={12}", ConfigurationManager.AppSettings["ApiURL"], "AdminDashboard/GetGridData", null, null, null, null, null, null, null, null, null, null, null));
                        break;
                }
                var result = (new APICallHelper()).Get(APIURL.ToString()).Content.ReadAsStringAsync().Result;
                return Json(JsonConvert.DeserializeObject<List<usp_getAdminDashboardData_Result>>(result.ToString()), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        [HttpPost]
        public ActionResult GetEditClientView(string id)
        {
           
            String APIURL = string.Format("{0}/{1}?id={2}", Constants.ApiURL, "SalesRepData/GetClientData", id);
            var result = (new APICallHelper()).Get(APIURL).Content.ReadAsStringAsync().Result;
            var data = JsonConvert.DeserializeObject<usp_getUserDetails_Result>(result.ToString());
            AdminDashboardModel model = new AdminDashboardModel();
            model.ClientDetails = data;
            model.ClientTypeList = DataHelper.GetClientTypeSelectList(data.ClientType);
            model.CampaignList = DataHelper.GetCampaignSelectList(data.CampaignTypeId.ToString());
            model.SalesRepList = DataHelper.GetSalesRep(data.SalesRepId!=null?data.SalesRepId:null);
            model.PlanList = DataHelper.GetPlanSelectList(data.PlanId.ToString());
            model.TimeZone = DataHelper.GetTimeZone(model.ClientDetails.TimeZoneName);
            model.IPPoolList = DataHelper.GetIPPoolList(data.IPPoolId.ToString());
            model.SubscriberList = DataHelper.GetSubscriberList(model.ClientDetails.NoOfSubscribersMax, model.ClientDetails.PlanId);
            if(model.ClientDetails.MonthlyCredit == 0.ToString())
            {
                model.ClientDetails.MonthlyCredit = "Unlimited Emails";
            }
            return PartialView("EditClientView", model);

        }
        [HttpPost]
        public JsonResult UpdateUserProfile(AdminDashboardModel userAdminDataViewModel)
        {
            try
            {
                var context = new EmailMarketingDbEntities();
                var userPro = context.UserProfiles.Where(x => x.Id == userAdminDataViewModel.ClientDetails.Id).FirstOrDefault();
                var userPlan = context.UserPlans.Where(x => x.UserId == userAdminDataViewModel.ClientDetails.Id && x.IsActive == true).FirstOrDefault();
                //var notes = context.SalesPortalRepNotes.Where(x => x.UserId == userAdminDataViewModel.UserId).OrderByDescending(r => r.LastModDate).ThenByDescending(r => r.CreatedDate).FirstOrDefault();
                if (userPro != null)
                {
                    if (userAdminDataViewModel.ClientDetails.SalesRepId != null && (userAdminDataViewModel.ClientDetails.SalesRepId != userPro.SalesRepId || userPro.SalesRepId == null))
                    {
                        string oldSalesRepId = userPro.SalesRepId;
                        var oldSlaesRepDetails = context.SalesRepProfiles.Find(oldSalesRepId);
                        if (oldSlaesRepDetails != null)
                        {
                            oldSlaesRepDetails.NoOfClients = oldSlaesRepDetails.NoOfClients - 1;
                        }

EM.Web/Areas/Admin/Views/Dashboard/AddEditNotes.cshtml
@model EM.Web.Areas.Admin.Models.NoteViewModel

<style type="text/css">
    .preNotePane {
        clear: both;
        padding: 10px 0px;
        border-bottom: 1px solid #ccc;
    }
    .pNdescription {
        clear: both;
        padding: 5px 0 0;
        font-size: 12px;
    }
    .PreNotwrap {
        max-height: 200px;
        overflow-y: auto;
        padding: 15px;
    }
</style>

<div class="modal" role="dialog" id="repNote">
    <div class="modal-dialog modal-dialog-centered  modal-sm" role="document">
        <div class="modal-content">
            @using (Ajax.BeginForm("AddNote", "Dashboard", new { area = "Admin" }, new AjaxOptions() { HttpMethod = "POST", OnBegin = "return onAddNote();", OnSuccess = "onAddNoteSucess", OnFailure = "onAddNoteFailure" }))
            {

                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title">
                        <img src="~/Content/imagesHome/note-ic.png" style="width:20px;" alt="">
                        Notes
                    </h4>
                    
                </div>

                <div class="modal-body">
                    <div class="row">
                        <div class="col-md-12">
                            @Html.HiddenFor(m => m.newNote.NoteId)
                            @Html.HiddenFor(m => m.newNote.UserId)
                            <div class="form-row">
                                <label class="control-label">Description</label>
                                <a class="creat_new pull-right text-13" href="#!" onclick="Clear();">Clear</a>
                                @Html.TextAreaFor(m => m.newNote.NoteDescription, new { @id = "txtNotes", @class = "form-control", @rows = "5" })
                                @*<textarea type="text" id="" class="form-control" rows="3"></textarea>*@
                                <span id="noteError" class="RequiredField"></span>
                                &nbsp;
                            </div>
                            <div class="form-row">
                                <label class="control-label"><i class="fa fa-calendar-check-o"></i> Follow Up Date</label>
                                @Html.TextBoxFor(m => m.newNote.FollowUpDate, new { @id = "followDT", @class = "form-control" })
                                @*<input type="text" id="followDT" class="form-control" placeholder="Follow Up" />*@
                                <span id="followError" class="RequiredField"></span>
                                &nbsp;
                            </div>
                            <div class="form-row">
                                <label class="control-label">Follow Up Type</label>
                                @Html.DropDownListFor(x => x.newNote.NoteTypeId, new List<SelectListItem> {
                                                                    new SelectListItem { Text = "Call", Value = "1" },
                                                                    new SelectListItem { Text = "Text", Value = "2" },
                             new SelectListItem { Text = "Email", Value = "3" },
                             new SelectListItem { Text = "Others", Value = "4" }}, "Select", new { @id = "notetype", @class = "form-control" })

                                <span id="noteTypeError" class="RequiredField"></span>
                                &nbsp;
                            </div>
                            <div class="form-row">
                                <label class="control-label">Time Zone</label>
                                @Html.DropDownListFor(x => x.newNote.TimeZone, Model.TimeZoneList, "--Select--", new { @id = "timeZone", @class = "form-control" })
                                <span id="timeZoneError" class="RequiredField"></span>
                                &nbsp;
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-md-6" style="float: right;text-align: right;">
                            <button type="button" class="btn btn-warning" data-dismiss="modal" id="salesRepAddNoteModel">Close</button>
                            @if (Model.newNote.NoteId == 0)
                            {
                                <button type="submit" class="btn btn_default" id="btnNoteSubmit">Add</button>
                            }
                            else
                            {
                                <button type="submit" class="btn btn_default" id="btnNoteSubmit">Update</button>
                            }
                        </div>
                    </div>

                    <h4 class="prv-title margin-top-5">Previous Notes:</h4>
                    <div class="PreNotwrap text-14">
                        @if (Model.noteList != null && Model.noteList.Count() > 0)
                        {
                            foreach (var item in Model.noteList)
                            {
                                var data = Newtonsoft.Json.JsonConvert.SerializeObject(item);
                                var CreatedDate = item.CreatedDate == null ? DateTime.UtcNow : Convert.ToDateTime(item.CreatedDate);
                                var FormattedDate = string.Format("{0} {1}/{2}/{3}", CreatedDate.Date.ToString("dddd"), CreatedDate.Month, CreatedDate.Day, CreatedDate.Year);
                                <div class="row preNotePane">
                                    <div class="col-md-12 text-13">
                                        <div class="col-md-8">
                                            <span class="text-bold">
                                                @FormattedDate by @item.CreatedBy
                                            </span>
                                        </div>
                                        <div class="col-md-3">
                                            <a onclick="editNote(@data)" href="#">Edit</a>
                                            |
                                            <a onclick="deleteNoteConfirmation(@item.NoteId)" href="#">Delete</a>
                                            <br />
                                        </div>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-10 pNdescription">
                                            <span class="text-13"> @item.NoteDescription</span>

                                        </div>

                                    </div>

                                </div>
                            }
                        }
                        else
                        {
                            <div class="row">
                                <div class="col-md-12">
                                    No Record Found
                                </div>
                            </div>
                        }

                    </div>
                </div>
               
            }
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        preventEnterForSubmittingForm();
    });
        </script>

EM.Web/Areas/Admin/Views/Dashboard/EditClientView.cshtml
@model EM.Web.Areas.Admin.Models.AdminDashboardModel
@{
    ViewBag.Title = "EditClientView";
}

@using (Ajax.BeginForm("UpdateUserProfile", "Dashboard", new { area = "Admin" }, new AjaxOptions() { HttpMethod = "POST", OnBegin = "return onBegin();", OnSuccess = "onSuccess", OnFailure = "onFailure" }))
{
    <div class="modal fade" id="updateDetails" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <!--Content-->
            <div class="modal-content">
                <!--Header-->
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h4 class="modal-title" id="myModalLabel">Edit Admin Dashboard</h4>
                </div>
                <!--Body-->
                <div class="modal-body edt-pop">
                    @Html.HiddenFor(m => m.ClientDetails.Id)
                    <div class="row">
                        <div class="input-field-model">
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="form2">Sales Rep</label>
                                    @Html.DropDownListFor(x => x.ClientDetails.SalesRepId, Model.SalesRepList, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="form2">Client Type</label>
                                    @Html.DropDownListFor(x => x.ClientDetails.ClientType, Model.ClientTypeList, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="input-field">
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="">Member Type</label>
                                    @Html.DropDownListFor(x => x.ClientDetails.PlanId, Model.PlanList, new { @class = "form-control", onchange = "GetSubscriberDashboardList()" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="">No.Of Subscriber</label>
                                    @Html.DropDownListFor(x => x.ClientDetails.PackageId, Model.SubscriberList, new { @class = "form-control", onchange = "GetPackageDetail()" })
                                </div>
                            </div>
                        </div>
                        <div class="input-field">
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="">Follow Up</label>
                                    @Html.TextBoxFor(m => m.ClientDetails.FollowUpDate, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="">
                                    <label for="form2">Monthly Credit</label>
                                    @Html.TextBoxFor(m => m.ClientDetails.MonthlyCredit, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="input-field">
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="form2">MNTH Bill</label>
                                    @Html.TextBoxFor(m => m.ClientDetails.BillingAmount, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="">Next Billing Date</label>
                                    @Html.TextBoxFor(m => m.ClientDetails.NextPackageUpdateDate, new { @class = "form-control" })
                                </div>
                            </div>

                        </div>
                        <div class="input-field">
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="">CHRG Date</label>
                                    @Html.TextBoxFor(m => m.ClientDetails.PackageUpdateDate, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="">Billing Status</label>
                                    @Html.DropDownListFor(m => m.ClientDetails.BillingStatus, new List<SelectListItem> {
                                    new SelectListItem { Text = "Active", Value = "1" },
                                    new SelectListItem { Text = "InActive", Value = "-1" }, }, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>
                        <div class="input-field">
                            <div class="col-sm-6">
                                <div class="">
                                    <label>Email Sending</label>
                                    @Html.DropDownListFor(m => m.ClientDetails.EmailSending, new List<SelectListItem> {
                                     new SelectListItem { Text = "ON", Value = "true" },
                                     new SelectListItem { Text = "OFF", Value = "false" }, }, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="">
                                    <label>CSV Upload</label>
                                    @Html.DropDownListFor(m => m.ClientDetails.IsCSVActive, new List<SelectListItem> {
                                   new SelectListItem { Text = "Active", Value = "true" },
                                   new SelectListItem { Text = "InActive", Value = "false" }, }, new { @class = "form-control" })
                                </div>
                            </div>

                        </div>
                        <div class="input-field">
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="">Account Status</label>
                                    @Html.DropDownListFor(m => m.ClientDetails.IsActive, new List<SelectListItem> {
                                  new SelectListItem { Text = "Active", Value = "true" },
                                  new SelectListItem { Text = "InActive", Value = "false" }, }, new { @class = "form-control" })
                                </div>
                            </div>

                            <div class="col-sm-6">
                                <div class="">
                                    <label for="form2">Time Zone</label>
                                    @Html.DropDownListFor(x => x.ClientDetails.TimeZoneID, Model.TimeZone, "Select", new { @class = "form-control" })
                                </div>
                            </div>

                        </div>
                        <div class="input-field-model">
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="form2">IP Pool</label>
                                    @Html.DropDownListFor(x => x.ClientDetails.IPPoolId, Model.IPPoolList, "Select", new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="">
                                    <label for="form2">Referral Code</label>
                                    @Html.TextBoxFor(x => x.ClientDetails.PromotionCode, new { @class = "form-control" })
                                </div>
                            </div>
                        </div>

                      
                        <!--Footer-->
                        <div class="modal-footer">
                            <button type="button" class="btn btn-warning" data-dismiss="modal" id="updateAdminUserDataModel">Close</button>
                            <button type="submit" class="btn btn_default">Save changes</button>
                        </div>
                    </div>
                    <!--/.Content-->
                </div>
            </div>
        </div>
    </div>
    <input type="hidden" name="APIURL" id="APIURL" value="@Constants.ApiURL" />
}
<script>
    $(document).ready(function () {
        preventEnterForSubmittingForm();
        var fDate = '@Model.ClientDetails.FollowUpDate';
        var packageUpdateDate = '@Model.ClientDetails.NextPackageUpdateDate';
        var packageDate = '@Model.ClientDetails.PackageUpdateDate';
        $('#ClientDetails_FollowUpDate').val(fDate);
        initSignalDatePicker($('#ClientDetails_FollowUpDate'));
        if (fDate == '') {
            $('#ClientDetails_FollowUpDate').val('');
        }
        $('#ClientDetails_NextPackageUpdateDate').val(packageUpdateDate);
        initSignalDatePickerWithTime($('#ClientDetails_NextPackageUpdateDate'));
        if (packageUpdateDate == '') {
            $('#ClientDetails_NextPackageUpdateDate').val('');
        }
        $('#ClientDetails_PackageUpdateDate').val(packageDate);
        initSignalDatePickerWithTime($('#ClientDetails_PackageUpdateDate'));
        if (packageDate == '') {
            $('#ClientDetails_PackageUpdateDate').val('');
        }

    })
</script>